language: node_js
node_js:
  - 8.10.0
deploy:
  provider: npm
  email: {{{author.npm_email}}}
  api_key:
    secure: "{{{authentication.npm_token}}}"
  on:
    branch: master
    tags: true
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
